### ISSUE TITLE
There are no issue but I want to ask this

### ISSUE THREAD

**Issue by longbro5567** [IllusionMods/KKManager#15]
![image](https://user-images.githubusercontent.com/61102004/74622254-b69bb200-5172-11ea-96d2-dd012c926bf7.png)
Some mod file when I installed and they announced that error or these files were removed. Can you show me the solution, please?

**Comment by longbro5567** [comment]
And how can we apply mod to game because I don't see any change after I download these mods.

**Comment by ManlyMarco** [comment]
Assuming you have your plugins installed correctly the mods will appear as normal. I don't see anything wrong on the screenshot. If you're unsure about how to mod the game then consider using the KK HF Patch instead since it's aimed at beginners. For general help like this you should join the [discord server](https://discord.gg/hevygx6) since there's usually someone present that can answer you right away.
